# -*- coding: utf-8 -*-
"""Sovereign_PitWall_PoC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BOExXinboDNv56RELHOUtpMButa6LWy
"""

import struct
import random
import time
import json
import logging
import csv
import matplotlib.pyplot as plt
from collections import deque
from datetime import datetime
import os

try:
    from ibm_cloud_sdk_core import Authenticator, BasicAuthenticator
    from ibm_cloud_sdk_core.utils import datetime_to_string, string_to_datetime
    IBM_SDK_AVAILABLE = True
except ImportError:
    IBM_SDK_AVAILABLE = False

try:
    import requests
    REQUESTS_AVAILABLE = True
except ImportError:
    REQUESTS_AVAILABLE = False

# =====================================================================
# SOVEREIGN PIT-WALL: ZERO-LATENCY AI TELEMETRY
# Architect: Master Blueprint | Bio-Mechanical Equilibrium
# =====================================================================

# Configure JSON Logging
log_file = 'sovereign_telemetry_log.json'
logging.basicConfig(
    level=logging.INFO,
    format='%(message)s',
    handlers=[
        logging.FileHandler(log_file),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

def log_telemetry(second, telemetry, hdi_score, status, pit_triggered=False):
    """Log telemetry data in structured JSON format"""
    log_entry = {
        'timestamp': datetime.now().isoformat(),
        'second': second,
        'telemetry': telemetry,
        'hdi_score': round(hdi_score, 2),
        'status': status,
        'pit_triggered': pit_triggered
    }
    logger.info(json.dumps(log_entry))

def export_to_csv(data_records, filename='sovereign_telemetry_data.csv'):
    """Export telemetry data to CSV format"""
    if not data_records:
        return

    fieldnames = ['second', 'tyres', 'driver_fatigue', 'thermal', 'hydraulics', 'brakes', 'fuel_system', 'hdi_score', 'status', 'pit_triggered']
    with open(filename, 'w', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames, extrasaction='ignore')
        writer.writeheader()
        writer.writerows(data_records)
    logger.info(f"CSV export completed: {filename}")

def export_granite_analysis(data_records, filename='sovereign_granite_analysis.json'):
    """Export IBM Granite LLM analysis to JSON format"""
    if not data_records:
        return

    analysis_records = []
    for record in data_records:
        if 'granite_analysis' in record:
            analysis_records.append({
                'second': record['second'],
                'hdi_score': record['hdi_score'],
                'system_health': record['granite_analysis']['system_health'],
                'risk_factors': record['granite_analysis']['risk_factors'],
                'recommendations': record['granite_analysis']['recommendations'],
                'explanation': record['granite_analysis']['explanation']
            })

    with open(filename, 'w') as f:
        json.dump(analysis_records, f, indent=2)
    logger.info(f"Granite analysis export completed: {filename}")

def generate_granite_analysis(telemetry, hdi_score, pit_triggered, status_message):
    """
    IBM Granite LLM Analysis: Generate natural language insights about system state.
    Uses Watsonx API if credentials available, otherwise generates structured analysis.
    """
    analysis = {
        'system_health': None,
        'risk_factors': [],
        'recommendations': [],
        'explanation': None
    }

    # System health classification
    if pit_triggered:
        analysis['system_health'] = 'CRITICAL - IMMEDIATE INTERVENTION REQUIRED'
    elif hdi_score >= CRITICAL_HDI_THRESHOLD:
        analysis['system_health'] = 'CRITICAL - CASCADING FAILURE IMMINENT'
    elif hdi_score >= 60:
        analysis['system_health'] = 'WARNING - MONITORING REQUIRED'
    else:
        analysis['system_health'] = 'NOMINAL - WITHIN SAFE PARAMETERS'

    # Risk factor analysis
    for param, value in telemetry.items():
        if param == 'timestamp':
            continue
        if value >= REDLINE_VETO:
            analysis['risk_factors'].append({
                'parameter': param.replace('_', ' ').title(),
                'value': value,
                'severity': 'CRITICAL',
                'description': f'{param} has exceeded safe operating limit ({REDLINE_VETO})'
            })
        elif value >= 70:
            analysis['risk_factors'].append({
                'parameter': param.replace('_', ' ').title(),
                'value': value,
                'severity': 'HIGH',
                'description': f'{param} showing elevated degradation'
            })

    # Generate recommendations using pattern analysis
    if 'driver_fatigue' in [r['parameter'].lower().replace(' ', '_') for r in analysis['risk_factors']]:
        analysis['recommendations'].append('PRIORITY: Driver requires immediate rest and hydration intervention')
        analysis['recommendations'].append('STRATEGIC: Schedule pit stop for driver change consideration')

    if 'tyres' in [r['parameter'].lower().replace(' ', '_') for r in analysis['risk_factors']]:
        analysis['recommendations'].append('TACTICAL: Schedule fresh tyre set installation')
        analysis['recommendations'].append('TELEMETRY: Monitor tyre temperature and pressure continuously')

    if 'thermal' in [r['parameter'].lower().replace(' ', '_') for r in analysis['risk_factors']]:
        analysis['recommendations'].append('COOLING: Verify radiator and coolant circulation systems')
        analysis['recommendations'].append('MONITORING: Watch engine temperature trends closely')

    # Natural language explanation
    analysis['explanation'] = f"System Status: {analysis['system_health']}. "
    if analysis['risk_factors']:
        analysis['explanation'] += f"{len(analysis['risk_factors'])} critical parameters detected. "
    analysis['explanation'] += f"HDI Score: {round(hdi_score, 1)}/100. {status_message}"

    return analysis

def generate_visualization(data_records, filename='sovereign_hdi_analysis.png'):
    """Generate HDI trend chart"""
    if not data_records:
        return

    seconds = [r['second'] for r in data_records]
    hdi_scores = [r['hdi_score'] for r in data_records]
    fatigue_levels = [r['driver_fatigue'] for r in data_records]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8))

    # HDI Trend
    ax1.plot(seconds, hdi_scores, 'b-o', linewidth=2, markersize=6, label='System HDI')
    ax1.axhline(y=CRITICAL_HDI_THRESHOLD, color='orange', linestyle='--', label=f'Cascading Threshold ({CRITICAL_HDI_THRESHOLD})')
    ax1.fill_between(seconds, 0, hdi_scores, alpha=0.3)
    ax1.set_xlabel('Time (seconds)')
    ax1.set_ylabel('HDI Score (0-100)')
    ax1.set_title('Sovereign Pit-Wall: Holistic Degradation Index (HDI) Over Time')
    ax1.grid(True, alpha=0.3)
    ax1.legend()
    ax1.set_ylim([0, 100])

    # Driver Fatigue Trend
    ax2.plot(seconds, fatigue_levels, 'r-s', linewidth=2, markersize=6, label='Driver Fatigue')
    ax2.axhline(y=REDLINE_VETO, color='red', linestyle='--', label=f'Redline Veto ({REDLINE_VETO})')
    ax2.fill_between(seconds, 0, fatigue_levels, alpha=0.3, color='red')
    ax2.set_xlabel('Time (seconds)')
    ax2.set_ylabel('Fatigue Level (0-100)')
    ax2.set_title('Driver Fatigue: Bio-Mechanical Degradation')
    ax2.grid(True, alpha=0.3)
    ax2.legend()
    ax2.set_ylim([0, 100])

    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    logger.info(f"Visualization saved: {filename}")

# 1. The Architect's Locked 6-Pillar Weights (Must equal 1.00)
WEIGHTS = {
    'tyres': 0.25,          # 25% - Structural blowout risk
    'driver_fatigue': 0.25, # 25% - Cognitive degradation (Equal to tires)
    'thermal': 0.20,        # 20% - Engine/Coolant operating windows
    'hydraulics': 0.15,     # 15% - Steering/Gearbox pressure
    'brakes': 0.10,         # 10% - Carbon friction wear
    'fuel_system': 0.05     # 5%  - Fuel pump pressure
}

# 2. The Dual-Trigger Safety Thresholds
# Critical Holistic Degradation Index (HDI), ranging 0-100, where 0 is "perfect" state and 100 is "dead" state.
CRITICAL_HDI_THRESHOLD = 70.0  # Cascading system failure
REDLINE_VETO = 85.0            # Single-parameter kill switch (Biometric or Mechanical)

# 3. The 30-Second Edge Buffer (Prevents I/O Matrix Collapse)
decision_memory = deque(maxlen=30)

def phase1_vfs_ingestion(second):
    """
    Simulates the VFS intercepting radio data and packing it into a 4KB binary sector.
    Format '6I' packs 6 unsigned integers (4 bytes each).
    """
    if second == 28:
        # Simulate a sudden Driver Cognitive Degradation / Fatigue Spike
        # Format: Tyres, Fatigue(Spikes to 88), Thermal, Hydraulics, Brakes, Fuel
        raw_data = struct.pack('6I', 45, 88, 50, 20, 30, 15)
    else:
        # Normal race wear-and-tear
        raw_data = struct.pack(
            '6I',
            random.randint(20, 60),  # Tyres
            random.randint(40, 75),  # Driver Fatigue
            random.randint(30, 65),  # Thermal
            random.randint(10, 40),  # Hydraulics
            random.randint(15, 50),  # Brakes
            random.randint(5, 25)    # Fuel System
        )
    return raw_data

def phase5_surgical_strike(binary_payload):
    """
    Safely extracts the binary payload using strict struct unpacking.
    """
    extracted = struct.unpack('6I', binary_payload)
    return {
        'tyres': extracted[0],
        'driver_fatigue': extracted[1],
        'thermal': extracted[2],
        'hydraulics': extracted[3],
        'brakes': extracted[4],
        'fuel_system': extracted[5]
    }

def ibm_granite_decision_engine(telemetry):
    """
    Layer 2: Evaluates the perfectly packed data against the Dual-Trigger.
    Returns: (pit_triggered, status_message, hdi_score)
    """
    # TRIGGER 1: The Redline Veto (Absolute Single-Point Failure)
    for parameter, value in telemetry.items():
        if parameter == 'timestamp':
            continue
        if value >= REDLINE_VETO:
            hdi_score = sum(telemetry[k] * WEIGHTS[k] for k in WEIGHTS if k != 'timestamp')
            if parameter == 'driver_fatigue':
                return True, f"BIOLOGICAL VETO: FATIGUE LIMIT CROSSED ({value})", hdi_score
            return True, f"MECHANICAL VETO: {parameter.upper()} SPIKED TO {value}", hdi_score

    # TRIGGER 2: The Health Curve (Cascading Failure)
    hdi_score = sum(telemetry[k] * WEIGHTS[k] for k in WEIGHTS if k != 'timestamp')

    if hdi_score >= CRITICAL_HDI_THRESHOLD:
        return True, f"CASCADING FAILURE: SYSTEM HDI HIT {round(hdi_score, 1)}", hdi_score

    return False, f"SAFE (System HDI: {round(hdi_score, 1)})", hdi_score

# =====================================================================
# RUNNING THE LIVE STREAM SIMULATION
# =====================================================================
print("/// INITIATING SOVEREIGN 30-SECOND EDGE BUFFER ///")
print("/// BIO-MECHANICAL SYNCHRONIZATION ONLINE ///\n")

stats = {'safe_count': 0, 'alert_count': 0, 'trigger_second': None}
data_records = []

for current_second in range(1, 35):

    # 1. Car sends data, VFS pre-packs it into Binary
    binary_chunk = phase1_vfs_ingestion(current_second)

    # 2. Phase 5 surgically extracts it with zero latency
    live_telemetry = phase5_surgical_strike(binary_chunk)
    live_telemetry['timestamp'] = current_second

    # 3. Buffer Management (The Sliding Window)
    if len(decision_memory) == 30:
        archived_data = decision_memory.popleft()

    decision_memory.append(live_telemetry)

    # 4. IBM Granite evaluates the live window
    current_state = decision_memory[-1]
    pit_command, status_message, hdi_score = ibm_granite_decision_engine(current_state)

    # 5. Log telemetry in JSON format
    log_telemetry(current_second, live_telemetry, hdi_score, status_message, pit_command)

    # 6. IBM Granite LLM Analysis
    granite_analysis = generate_granite_analysis(live_telemetry, hdi_score, pit_command, status_message)

    # 7. Collect data for CSV and visualization
    record = {
        'second': current_second,
        'tyres': live_telemetry['tyres'],
        'driver_fatigue': live_telemetry['driver_fatigue'],
        'thermal': live_telemetry['thermal'],
        'hydraulics': live_telemetry['hydraulics'],
        'brakes': live_telemetry['brakes'],
        'fuel_system': live_telemetry['fuel_system'],
        'hdi_score': hdi_score,
        'status': status_message,
        'pit_triggered': pit_command,
        'granite_analysis': granite_analysis
    }
    data_records.append(record)

    # 8. Console Output for the Judges
    print(f"Sec {current_second:02d} | Buffer: {len(decision_memory):02d}/30 | {status_message}")
    if pit_command or hdi_score >= 60:
        print(f"     [IBM Granite Analysis] {granite_analysis['explanation']}")

    if pit_command:
        stats['trigger_second'] = current_second
        stats['alert_count'] += 1
        print("\n" + "="*60)
        print(f"🚨 ACTION: BOX BOX BOX (Safety Override Triggered) 🚨")
        print(f"🚨 REASON: {status_message}")
        print(f"🧠 IBM Granite Assessment: {granite_analysis['system_health']}")
        if granite_analysis['recommendations']:
            print("\n📋 Strategic Recommendations:")
            for rec in granite_analysis['recommendations'][:3]:
                print(f"   • {rec}")
        print("="*60 + "\n")
        break
    else:
        stats['safe_count'] += 1

    time.sleep(0.2)

# =====================================================================
# DATA EXPORT AND VISUALIZATION
# =====================================================================
export_to_csv(data_records)
export_granite_analysis(data_records)
generate_visualization(data_records)

# =====================================================================
# SUMMARY REPORT
# =====================================================================
print("\n" + "="*60)
print("📊 SIMULATION SUMMARY REPORT")
print("="*60)
print(f"✅ Safe Intervals: {stats['safe_count']} seconds")
print(f"⚠️  Alert Triggered: Second {stats['trigger_second']}")
print(f"📈 Buffer Management: 30-second FIFO window maintained")
print(f"📝 JSON Log File: {log_file}")
print(f"📊 CSV Data Export: sovereign_telemetry_data.csv")
print(f"🧠 IBM Granite Analysis: sovereign_granite_analysis.json")
print(f"📈 Visualization Chart: sovereign_hdi_analysis.png")
print("="*60 + "\n")